import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { injected } from "../components/wallet/connector";
import { useWeb3React } from '@web3-react/core';

export default function Home() {
  const { 
    active, // wallet connected?
    account, // blockchain address
    library, // web3 or ethers
    connector, // current connector (injected connector for MetaMask)
    activate, // method to connect to wallet
    deactivate // method to disconnect from wallet
  } = useWeb3React();

  

  async function connect () {
    try {
      await activate(injected)
    } catch (error) {
      console.log()
    }
  }

  async function disconnect () {
    try {
      await deactivate()
    } catch (error) {
      console.log()
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={connect}>Connect to Metamask</button>
        <button onClick={disconnect}>Disconnect</button>
        {active ?  
          <span>Connected with <b>{account}</b></span> : 
          <span>Not connected</span>
        }
      </main>
    </div>
  )
}
