import Head from "next/head";
import styles from "../styles/Home.module.css";
import { injected } from "../components/wallet/connector";
import { Landing } from "../components/landing";
import { useWeb3React } from "@web3-react/core";
import { AddressDisplayEnum, ENSName } from "react-ens-name";
import { useEffect, useState } from "react";

export default function Home() {
  const {
    active, // wallet connected?
    account, // blockchain address
    library, // web3 or ethers
    connector, // current connector (injected connector for MetaMask)
    activate, // method to connect to wallet
    deactivate, // method to disconnect from wallet
  } = useWeb3React();

  async function connect() {
    try {
      await activate(injected);
    } catch (error) {
      console.log(error);
    }
  }

  async function disconnect() {
    try {
      console.log("network", library);
      console.log("connector", connector);
      await deactivate();
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Vote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>Starshot</h1>
        {!active ? (
          <button onClick={connect} className={styles.button}>
            Connect to Metamask
          </button>
        ) : (
          <div>
            <ENSName 
              address={account} 
              displayType={AddressDisplayEnum.FIRST4}
              withEllipses={true}
            />
            <button onClick={disconnect} className={styles.button}>
              Disconnect
            </button>
          </div>
        )}
      </header>

      <main className={styles.main}>
        {active ?(
          <Landing/>
        ) : (
          <p className={styles.description}>
            On-chain voting for DAOs on <b>Rinkeby Testnet</b>
          </p>
        )}
      </main>
    </div>
  );
}